#!/bin/bash
# Build - checkout version and Pull docker image to corp docker registry
while getopts "i:v:" option; do
  case "${option}" in
    i)
      IMAGE_NAME=${OPTARG};;
    v)
      VER=${OPTARG};;
  esac
done

if [ -z ${IMAGE_NAME} ];
  then
    echo "Usage: ./build -i IMAGE_NAME -v VER";
    exit;
fi

if [ -z ${VER} ];
  then
    echo "Usage: ./build -i IMAGE_NAME -v VER";
    exit;
fi

## purge any previous app folder
rm -rf app

## GIT CLONE the project in local app folder
git clone git@dsgithub.trendmicro.com:TrialCloud/${IMAGE_NAME}.git app
cd app

## checkout the provided version
git checkout ${VER}
cd ..

## build Docker Image
docker build --no-cache=true --build-arg VER=${VER} --build-arg IMAGE_NAME=${IMAGE_NAME} -t aws.registry.trendmicro.com/trialcloud/${IMAGE_NAME}:${VER} .

## Push Docker Image to the Docker Registry
docker push aws.registry.trendmicro.com/trialcloud/${IMAGE_NAME}:${VER}

## Purge local app folder
rm -rf app

